#!/bin/bash

# shellcheck shell=dash
# vim: syntax=sh:

. '/lib/live/config/common.logging'

# When your boot parameter string has gotten too long for your bootloader, you can place the X2Go-TCE-related parameters in a file instead
# This file may contain name=value pairs either separated by blanks, as in a regular boot parameter string, or one name=value pair on each line

if [ -s /boot/liveboot_params ] ; then
	logttycolon 'liveboot_params file found on local media.'
	if grep -q "/proc/cmdline" /proc/mounts ; then
		logttycolon 'liveboot_params file already bind-mounted on /proc/cmdline, nothing to do.'
	else
		logttycolon 'Assembling new cmdline from current cmdline and liveboot_params in '"'"'/boot/proc_cmdline'"'"'.'
		cat /proc/cmdline /boot/liveboot_params | tr ' ' '\n' | grep -v "^liveboot_params" | tr '\n' ' ' >/boot/proc_cmdline
		logttycolon 'Attempting bind-mount of '"'"'/boot/proc_cmdline'"'"' on top of '"'"'/proc/cmdline'"'"'.'
		if mount --bind -o ro /boot/proc_cmdline /proc/cmdline; then
			logttycolon 'Bind-mount successful.'
		else
			logttycolon 'WARNING: nothing bind-mounted on /proc/cmdline, please check why.'
		fi
	fi
fi
