#!/bin/sh

# shellcheck shell=dash

LockUser ()
{

# Output startup message
#
printf ' %s' 'lockuser'


# Set password
#
if grep -q "\W*nouser\W*" /proc/cmdline ; then
	passwd -l user >/dev/null
fi

}

LockUser

