#!/bin/dash

. '/lib/live/config/common.logging'

GetSSHHostKeysFromMedia ()
{
        # Output startup message
        #
	printf ' %s' 'getsshhostkeysfrommedia'
	(
		check_for_config (){
			if [ -d $1/config/sshdkeys ] ; then
				logtty "$(printf 'Keyfile directory found at '"'"'%s/config/sshdkeys'"'"'.' "${1}")"
				# any keyfile in the config dir will be copied over to live system
				for KEYFILE in $1/config/sshdkeys/ssh_host*key* ; do
					[ -e "$KEYFILE" ] && cp $KEYFILE /etc/ssh/ && KEYFLAG=1
					keyfile_name="$(basename "${KEYFILE}")"
					case "${keyfile_name}" in
						(*'.pub')
							chmod '644' "/etc/ssh/${keyfile_name}"
							;;
						(*)
							chmod '600' "/etc/ssh/${keyfile_name}"
					esac
				done
				# no keys present (as detected by flag not being set), but directory is there? Store keys.
				if [ -z "$KEYFLAG" ] ; then
					logtty "$(printf 'No keyfiles were found in the keyfile directory '"'"'%s/config/sshdkeys'"'"'.' "${1}")"
					ssh-keygen -A # make sure we have keyfiles for every key the server expects
					logtty "$(printf 'Attempting to copy current keyfiles to keyfile directory '"'"'%s/config/sshdkeys'"'"'.' "${1}")"
					if awk '$2=="'$1'" {print $4 }' /proc/mounts | tr ',' '\n' | grep -q '^ro$' ; then
						logtty "$(printf 'Attempting to remount '"'"'%s'"'"' with flags rw and sync.' "${1}")"
						if mount -o 'remount,rw,sync' "${1}" ; then
							logtty "$(printf 'Successfully remounted '"'"'%s'"'"'.' "${1}")"
							REMOUNT="rws"
						else
							logtty "$(printf 'Error remounting '"'"'%s'"'"'.' "${1}")"
						fi
					fi
					if ([ -z "$REMOUNT" ] || [ "$REMOUNT" = "rws" ]) && cp /etc/ssh/ssh_host*key* $1/config/sshdkeys/ ; then
						logtty 'Copying keyfiles succeeded.'
					else
						logtty 'Error copying keyfiles.'
					fi
					if [ -n "${REMOUNT}" ] && mount -o 'remount,ro' $1 ; then
						logtty "$(printf 'Remounted '"'"'%s'"'"' read-only.' "${1}")"
					else
						logtty "$(printf 'Error remounting '"'"'%s'"'"' read-only.' "${1}")"
					fi
					
				else
					if ps -C sshd >/dev/null 2>&1 ; then
						# reload sshd config
						logtty 'Reloading sshd config to activate new keyfiles.'
						if service ssh reload ; then
							logtty 'New keyfiles activated.'
						else
							logtty 'Error activating new keyfiles.'
						fi
					else
						logtty 'sshd not running (yet), so no reloading required.'
					fi
				fi
				return 0
			else
				return 1
			fi
		}

		while ! [ -c /dev/tty8 ] ; do
			logcon 'is waiting for tty8 to become available.'
			sleep 2
		done
                while ! service udev status >/dev/null; do
                        logtty 'Waiting for udev to start ...'
                        sleep 1;
                done
		logtty 'Waiting for udev to process all events ...'
		udevadm settle
		logtty '... all events have been processed.'

                # list devices (and mountpoints, if present)

		while true; do
			LABELLIST=$(ls -1 /dev/disk/by-label/ | sort -u | tr '\n' '|') # generated from /dev/disk/by-label/
			logtty "$(printf 'Status of /dev/disk/by-label: '"'"'%s'"'"'.' "${LABELLIST}")"

	                LABELMPLIST=$(lsblk -oLABEL,RM,NAME,MOUNTPOINT -rn)
			LSBLKLIST=$(echo "$LABELMPLIST" | grep -v "^ " | awk '{print $1}' | sort -u | tr '\n' '|') # generated from lsblk
			logtty "$(printf 'Status of lsblk: '"'"'%s'"'"'.' "${LSBLKLIST}")"
			[ "$LABELLIST" = "$LSBLKLIST" ] && break
			sleep 1
		done

                # search for our magic label
                X2GOTCELIVELABELS=$(echo "$LABELMPLIST" | awk '$1 == "X2GO-TCE-LIVE" { print $2 " " $3 " " $4}')

		[ -z "$X2GOTCELIVELABELS" ] && logtty 'No matching '"'"'magic'"'"' label(s) found.'

                # block device list, non-removable first (for security - we don't want USB media to be able to override keys on fixed disks)
                BLOCKDEVS="$(echo "$X2GOTCELIVELABELS" | awk '$1 == "0" {print $2}' ) $(echo "$X2GOTCELIVELABELS" | awk '$1 == "1" {print $2}' )"

		# for every block device in our list, do ...
		for BLOCKDEV in $BLOCKDEVS; do 
			# check if it also appears in the list of devices carrying our magic label
			# this should always be the case since we changed how BLOCKDEVS is assembled
			NEXTDEVICE=$(echo "$X2GOTCELIVELABELS" | grep "$BLOCKDEV")
			if [ -n "$NEXTDEVICE" ] ; then
				# now figure out the mountpoint
				MNTPT=$(echo $NEXTDEVICE | awk '{print $3}')
				# and the device name
				NEXTDEVICE=$(echo $NEXTDEVICE | awk '{print $2}')
				logtty "$(printf 'Checking status of Device '"'"'%s'"'"' for BLOCKDEV '"'"'%s'"'"'.' "${NEXTDEVICE}" "${BLOCKDEV}")"
				if [ -n "$MNTPT" ] ; then
					# If the mountpoint variable isn't empty, it means the device is already mounted.
					logtty "$(printf 'Device '"'"'%s'"'"' is mounted at: '"'"'%s'"'"'.' "${NEXTDEVICE}" "${MNTPT}")"
					# so let's check if we have a config directory at that mountpoint.
					if check_for_config $MNTPT ; then
						# if we managed to pull a config off of it (or save one on it), we make a note of this ...
						echo "$LABELMPLIST" >/var/lib/live/config/opensshkeys
						# and quit right here.
						exit 0
					fi
				else
					# So there's no active mount for the device with our magic label ...
					logtty "$(printf 'Device '"'"'%s'"'"' is not mounted.' "${NEXTDEVICE}")"
					# let's see if this is a fixed disk.
					if [ $(lsblk -oRM -nl /dev/$BLOCKDEV) -eq 0 ] ; then
						# yes, it is, so let's go ahead and try to mount it ...
						logtty "$(printf 'Device '"'"'%s'"'"' is a fixed disk, mounting ...' "${NEXTDEVICE}")"
						# obviously, we need a mountpoint for it ...
						mkdir -p /media/fixeddisks/$NEXTDEVICE
						# and now we can try to mount it. Let's do it in readonly mode, just to play it safe.
						# a read-write remount is only attempted within check_for_config if it finds an empty
						# sshd keys directory.
						mount -o ro /dev/$NEXTDEVICE /media/fixeddisks/$NEXTDEVICE
						# If we managed to pull a config off of it (or save one on it), ...
						if check_for_config /media/fixeddisks/$NEXTDEVICE ; then
							# we umount, then make a note that we succeeded ...
							umount /media/fixeddisks/$NEXTDEVICE
							echo "$LABELMPLIST" >/var/lib/live/config/opensshkeys
							# and quit right here.
							exit 0
						fi
						# If we didn't succeed in pulling a config, we still need to umount what we mounted.
						umount /media/fixeddisks/$NEXTDEVICE
					else
						# If a removable disk hasn't been mounted by the automounter, something's amiss and we shouldn't try to meddle with it.
						# So let's make a note of this and move on.
						logtty "$(printf 'Device '"'"'%s'"'"' is a removable disk, not mounted by automounter, skipping.' "${NEXTDEVICE}")"
					fi
				fi
			fi
		done
		# Now let's leave a mark saying that we're done, so the next script can pick up on it.
		echo "$LABELMPLIST" >/var/lib/live/config/opensshkeys
	) &
}

GetSSHHostKeysFromMedia
