#!/bin/sh

. '/lib/live/config/common.logging'

# this is not /bin/bash, so "echo -e" is not supported, but the default when calling "echo"

prepare_tempdir ()
{ # prepare temporary directory by filling it with the contents of our download folder
	# Now we'll copy the content of the X2Go-live-download folder to our tempdir
	# this is so we can run wget in update mode (-N) or rsync without needing
	# write access to our boot medium (write access means increased wear and tear,
	# and we want to avoid that especially for media that has no wear-leveling
	# like CF cards)
	#
	logconcolon 'Preparing tempdir ...'
	while ! rsync -aPv --inplace --modify-window=1 $DOWNLOADPATH/ $TEMPDIR; do
		logconcolon 'Sleeping 30 seconds ...'
		sleep 30
		logconcolon 'Retrying ...'
	done
	echo " done."
}

check_timestamp ()
{ # this attempts to download a timestamp file
	logconcolon 'starting timestamp download ...'
	if ! $DOWNLOADCOMMANDFORTIMESTAMP; then
		return 1
	else
		RUNNINGVERSION=$(stat -c %Y /lib/live/mount/rootfs/filesystem.squashfs/lib)
		if [ $RUNNINGVERSION -ge $(cat $TEMPDIR/x2go-tce-timestamp) ] ; then
			return 5
		fi
	fi
	return 0
}

show_versions ()
{ # this prints the TCE versions that are stored on the local medium to the log output
	LISTOFTIMESTAMPFILES=$(find /lib/live/mount/findiso/boot -name "x2go-tce-timestamp")
	if [ -n "$LISTOFTIMESTAMPFILES" ]; then
		logconcolon 'List of locally stored TCE versions:'
		echo "--- BEGIN TIMESTAMPS ---" >/var/run/x2go-tce-timestamps
		for TIMESTAMPFILE in $LISTOFTIMESTAMPFILES; do 
			echo "$(cat $TIMESTAMPFILE);$(basename $(dirname $TIMESTAMPFILE));" >>/var/run/x2go-tce-timestamps
			logconcolon "$(printf '%s - %s - %s' "$(basename "$(dirname "${TIMESTAMPFILE}")")" "$(cat "${TIMESTAMPFILE}")" "$(date --date="@$(cat "${TIMESTAMPFILE}")")")"
		done
		sed -i "s/${RUNNINGSYSTEMNAME};$/${RUNNINGSYSTEMNAME};X/i" /var/run/x2go-tce-timestamps
		echo "---- END TIMESTAMPS ----" >>/var/run/x2go-tce-timestamps
	fi
}

umount_or_remount_ro ()
{ # change mount back to ro and sync
	if [ -n "$NTFSROOT" ] || [ -n "$RAMDISKMODE" ] ; then
		if umount $MOUNTPOINT; then
			logconcolon "$(printf 'Unmounted '"'"'%s'"'"'.' "${MOUNTPOINT}")"
		else
			logconcolon "$(printf 'Unable to unmount '"'"'%s'"'"'.' "${MOUNTPOINT}")"
		fi
	else	
		if mount -o 'remount,ro,sync' "${MOUNTPOINT}"; then
			logconcolon "$(printf 'Remounted '"'"'%s'"'"' ro and sync.' "${MOUNTPOINT}")"
		else
			logconcolon "$(printf 'Unable to remount '"'"'%s'"'"' ro and sync.' "${MOUNTPOINT}")"
		fi
	fi

}

cleanup () 
{ # discard contents of tmpfs, umount if necessary
	if [ -n "$NTFSROOT" ]; then
		logconcolon "$(printf 'Removing '"'"'%s/*'"'"'.' "${TEMPDIR}")"
		rm -rf $TEMPDIR/*
	else
		logconcolon "$(printf 'Unmounting '"'"'%s'"'"'.' "${TEMPDIR}")"
		umount $TEMPDIR
	fi
	if rmdir $TEMPDIR; then
		logconcolon "$(printf 'Removed empty directory '"'"'%s'"'"'.' "${TEMPDIR}")"
	else
		logconcolon "$(printf 'Could not remove directory '"'"'%s'"'"'.' "${TEMPDIR}")"
	fi
	if [ -n "$NTFSROOT" ] || [ -n "$RAMDISKMODE" ] ; then
		if grep -q "$MOUNTPOINT" /proc/mounts ; then
			logconcolon "$(printf "'"'%s'"'"' is mounted, attempting umount.' "${MOUNTPOINT}")"
			if umount $MOUNTPOINT; then
				logconcolon "$(printf 'Unmounted '"'"'%s'"'"'.' "${MOUNTPOINT}")"
			else
				logconcolon "$(printf 'Could not unmount '"'"'%s'"'"'.' "${MOUNTPOINT}")"
			fi
		fi
	fi
}

LiveAutoUpdateMain ()
{
# Output startup message
#
printf ' %s' 'live-autoupdater (backgrounding update task)'


# Background everything
#
(

	while ! [ -c /dev/tty8 ] ; do
		logcon 'is waiting for tty8 to become available.'
		sleep 2
	done

	# redirect all output to first available VT console
	#
	exec >/dev/tty8 2>&1

	# This is so grep, awk and sed will match the right terms regardless of LANG
	#
	unset LANG
	unset LC_ALL
	unset LC_MESSAGES

	# Define our mountpoint and check if we're capable of auto-updating
	NTFSROOT=$(sed -e 's/ \([^ ]*\)=/\n\1=/g' -e 's/\([^=]["'"'"']\) /\1\n/g' -e 's/ \([^ "'"'"']\)/\n\1/g' -e 's/ \([^ "'"'"']\)/\n\1/g' /proc/cmdline | awk -F '=' '/^ntfs-uuid/ { print $2 }' |  tr -dc 'a-zA-Z0-9_\-')
	if [ -n "$NTFSROOT" ]; then
		mkdir -p /lib/live/mount/ntfsroot
		# This is in case we've been passed an incomplete UUID and/or one with dashes
		# For example, "vol c:" on Windows will return the last 8 digits of the UUID
		# only, and separate them with a dash.
		if ! [ -L "/dev/disk/by-uuid/$NTFSROOT" ]; then
			NTFSROOT=$(echo $NTFSROOT | tr -d '-')
			if ! [ -L "/dev/disk/by-uuid/$NTFSROOT" ]; then
				NTFSROOT=$(basename $(echo /dev/disk/by-uuid/*$NTFSROOT | tr ' ' '\n' | head -1))
			fi
		fi

		if mount -t 'ntfs-3g' -o 'rw' "/dev/disk/by-uuid/${NTFSROOT}" '/lib/live/mount/ntfsroot' ; then
			logconcolon "$(printf 'Mounted '"'"'/dev/disk/by-uuid/%s'"'"'.' "${NTFSROOT}")"
		else
			logconcolon "$(printf 'Unable to mount '"'"'/dev/disk/by-uuid/%s'"'"'.' "${NTFSROOT}")"
		fi
		# TODO: Further error handling
		MOUNTPOINT="/lib/live/mount/ntfsroot/"
		# create a temporary directory
		TEMPDIR=$(mktemp -d --tmpdir=$MOUNTPOINT)
	else
		MOUNTPOINT="/lib/live/mount/findiso/"
		# create a temporary directory and mount a tmpfs there
		TEMPDIR=$(mktemp -d --tmpdir=/mnt)
		
		if [ -d /lib/live/mount/findiso/ ] ; then
			# if we have access to the entire filesystem, use the
			# directory size as base size for the current image - 
			# and if the download directory is even bigger, use that size
			IMGSIZE=$(du -s "/lib/live/mount/findiso/$(dirname $(sed -e 's/^.*findiso/findiso/' -e 's/ .*$//' /proc/cmdline | awk -F '=' '{ print $2 }' | tr -dc 'a-zA-Z0-9./ _\-'))" | awk '{ print $1}')
			IMGSIZEDOWNLOAD=$(du -s "/lib/live/mount/findiso/boot/X2Go-live-download" | awk '{ print $1}' || echo "0")
			[ $IMGSIZEDOWNLOAD -gt $IMGSIZE ] && IMGSIZE=$IMGSIZEDOWNLOAD
		else
			IMGSIZE=$(df /lib/live/mount/medium | awk ' /medium/ { print $2}')
		fi
		# multiply current size by 1.5 as safety margin
		mount -t 'tmpfs' -o "size=$((IMGSIZE*15/10))k" 'tmpfs' "${TEMPDIR}"

	fi

	# determine our booted environment as well as the other available ones
	RUNNINGSYSTEMFULLPATH=$(dirname $(readlink -m "$MOUNTPOINT/$(sed -e 's/ \([^ ]*\)=/\n\1=/g' -e 's/\([^=]["'"'"']\) /\1\n/g' -e 's/ \([^ "'"'"']\)/\n\1/g' -e 's/ \([^ "'"'"']\)/\n\1/g' /proc/cmdline | \
				awk -F'=' ' /^findiso=/ { print $2 }' | \
				tr -dc 'a-zA-Z0-9./ _\-')"))

	ALLSYSTEMSROOT=$(dirname $RUNNINGSYSTEMFULLPATH)
	RUNNINGSYSTEMNAME=$(basename $RUNNINGSYSTEMFULLPATH)

	# download url pointing to directory with all required files goes here
	DOWNLOADURL=$( sed -e 's/ \([^ ]*\)=/\n\1=/g' -e 's/\([^=]["'"'"']\) /\1\n/g' -e 's/ \([^ "'"'"']\)/\n\1/g' -e 's/ \([^ "'"'"']\)/\n\1/g' /proc/cmdline | \
		       awk -F'=' ' /^updateurl=/ { print $2 }' | \
		       tr -dc 'a-zA-Z0-9.:/?%_\-')

	if [ -z "$DOWNLOADURL" ]; then
		logconcolon 'No update URL. Exiting.'
		return 0
	fi

	if ! [ -d /lib/live/mount/findiso ] ; then
		logconcolon "'"'/lib/live/mount/findiso'"'"' directory not found. Scanning for partitions.'
		LISTOFPARTITIONS=$(grep -H ^0$ /sys/block/*/removable | awk -F '/' '{ print $4 }' | xargs -n 1 -I XXX fdisk -l /dev/XXX 2>/dev/null | awk '$0 ~ /Linux$/ { print $1}')
		TEMPMOUNT=$(mktemp -d -p /lib/live/mount/)
		FINDFILE=$(sed -e 's/ \([^ ]*\)=/\n\1=/g' -e 's/\([^=]["'"'"']\) /\1\n/g' -e 's/ \([^ "'"'"']\)/\n\1/g' -e 's/ \([^ "'"'"']\)/\n\1/g' /proc/cmdline | awk -F '=' '$1 == "findiso" { print $2 }' | tr -dc 'a-zA-Z0-9./ _\-')
		[ -z "$FINDFILE" ] && exit 0
		for PARTITION in $LISTOFPARTITIONS ; do
			mount -o 'ro' "${PARTITION}" "${TEMPMOUNT}"
			if ! [ -f "$TEMPMOUNT/$FINDFILE" ] ; then
				umount $TEMPMOUNT
			else
				umount $TEMPMOUNT
				rmdir $TEMPMOUNT
				mkdir /lib/live/mount/findiso
				if mount -o 'ro' "${PARTITION}" '/lib/live/mount/findiso' ; then
					logconcolon "$(printf 'mounted %s as '"'"'/lib/live/mount/findiso'"'"'.' "${PARTITION}")"
					RAMDISKMODE="yes"
				else
					logconcolon "$(printf 'error mounting %s as '"'"'/lib/live/mount/findiso'"'"'.' "${PARTITION}")"
				fi
				break
			fi
		done
	fi
	if ! [ -d /lib/live/mount/findiso ] ; then
		logconcolon 'Local update directory not found. Exiting.'
		return 0
	fi

	show_versions

	# Bandwidth limit goes here
	#
	#BWLIMITPERCENT=20 # in percent, numeric-only
	BWLIMITPERCENT=$(sed -e 's/ \([^ ]*\)=/\n\1=/g' -e 's/\([^=]["'"'"']\) /\1\n/g' -e 's/ \([^ "'"'"']\)/\n\1/g' -e 's/ \([^ "'"'"']\)/\n\1/g' /proc/cmdline | \
			 awk -F'=' ' /^bwlimit=/ { print $2 }' | \
			 tr -dc '0-9')
	if [ -z "$BWLIMITPERCENT" ]; then 
		BWLIMITPERCENT=20
		logconcolon 'Bandwidth limit not set. Defaulting to 20%.'
	fi


	# sleeping a random amount of time to ease load on the update server
	#
	MAXSLEEPTIME=$(sed -e 's/ \([^ ]*\)=/\n\1=/g' -e 's/\([^=]["'"'"']\) /\1\n/g' -e 's/ \([^ "'"'"']\)/\n\1/g' -e 's/ \([^ "'"'"']\)/\n\1/g' /proc/cmdline | \
		       awk -F'=' ' /^updatesleep=/ && $2 ~ /^[0-9]*$/ { print $2 }' | \
		       tr -dc '0-9')
	if [ -z "$MAXSLEEPTIME" ] || [ $MAXSLEEPTIME -lt 240 ] ; then
		MAXSLEEPTIME=900
	fi
	SLEEPTIME=0
	logconcolon "$(printf 'Calculating random update delay (120-%s seconds)...' "${MAXSLEEPTIME}")"
	# During startup, script is run with /bin/sh, 
	# even when #!/bin/bash is set,
	# so we need to improvise.
	RND=$(/bin/bash -c 'echo $RANDOM')
	SLEEPTIME=$((RND%MAXSLEEPTIME))
	if [ $SLEEPTIME -lt 120 ]; then
		SLEEPTIME=$((SLEEPTIME+120))
	fi
	logconcolon "$(printf 'Sleeping for %s seconds ...' "${SLEEPTIME}")"
	sleep $SLEEPTIME


	if ! (	[ -d "$MOUNTPOINT/boot/X2Go-live-download" ] && \
		( \
			[ -d "$MOUNTPOINT/boot/X2Go-live1" ] || \
			[ -d "$MOUNTPOINT/boot/X2Go-live2" ] \
		) \
	     ); then
		[ -n "$NTFSROOT" ] && umount $MOUNTPOINT
		logconcolon 'No directories suitable for update.'
		return 0 # directories missing, most likely not a writeable medium
	fi


	# define and figure out some paths that we will be needing later on
	#
	if [ -f "$MOUNTPOINT/syslinux.cfg" ]; then
		SYSLINUXPATH="$MOUNTPOINT/"
	elif [ -f "$MOUNTPOINT/syslinux/syslinux.cfg" ]; then
		SYSLINUXPATH="$MOUNTPOINT/syslinux/"
	elif [ -f "$MOUNTPOINT/menu.lst" ]; then
		GRUBPATH="$MOUNTPOINT/"
	elif  [ -f "$MOUNTPOINT/boot/menu.lst" ]; then
		GRUBPATH="$MOUNTPOINT/grub/"
	elif  [ -f "$MOUNTPOINT/boot/grub/menu.lst" ]; then
		GRUBPATH="$MOUNTPOINT/boot/grub/"
	else
		[ -n "$NTFSROOT" ] && umount $MOUNTPOINT
		logconcolon 'No suitable bootloader found.'
		return 1
	fi

	if [ "$RUNNINGSYSTEMNAME" = "X2Go-live1" ]; then
		OTHERSYSTEMNAME="X2Go-live2"
	elif [ "$RUNNINGSYSTEMNAME" = "X2Go-live2" ]; then
		OTHERSYSTEMNAME="X2Go-live1"
	else
		[ -n "$NTFSROOT" ] && umount $MOUNTPOINT
		logconcolon 'Unable to determine path/name of running system.'
		return 1
	fi
	OTHERSYSTEMFULLPATH=$(readlink -m "$ALLSYSTEMSROOT/$OTHERSYSTEMNAME")
	DOWNLOADPATH=$(readlink -m "$ALLSYSTEMSROOT/X2Go-live-download/")

	# Now let's figure out if we're supposed to use wget or rsync for downloading
	#
	if echo "$DOWNLOADURL" | grep -q "^http" || \
	   echo "$DOWNLOADURL" | grep -q "^ftp"
	   then
		DOWNLOADCOMMANDFORTIMESTAMP="wget -Nr -l 1 -nd -P $TEMPDIR \
				  --progress=bar:force \
				  $DOWNLOADURL/x2go-tce-timestamp"

		check_timestamp
		CTRC=$?
		if [ $CTRC -eq 1 ]; then
			logconcolon 'an error occurred during timestamp download; trying full download instead ...'
		elif [ $CTRC -eq 5 ]; then
			cleanup
			logconcolon "$(printf 'Nothing to do. - Files on server not newer than '"'"'%s'"'"'.' "${RUNNINGSYSTEMNAME}")"
			logconcolon "$(printf '('"'"'%s'"'"' is Version %s - %s).' "${RUNNINGSYSTEMNAME}" "${RUNNINGVERSION}" "$(date --date="@${RUNNINGVERSION}")")"
			return 0 	# current is newest, nothing to do, we want to avoid
					# unneccessary writes to the medium
		else
			: # NOP
		fi
		prepare_tempdir

		# Attempt to determine available bandwidth & to set BWLIMIT accordingly
		logconnlcolon 'Attempting to determine available bandwidth for wget.'
		wget -Nr -P /tmp/ -nd \
			--progress=bar:force "$DOWNLOADURL/x2go-tce-initrd.img" 2>&1 | \
			tee /tmp/dl.log
		cp --update "/tmp/x2go-tce-initrd.img" "$TEMPDIR"
		rm "/tmp/x2go-tce-initrd.img"
		SIZEFACTORSTRING=$(	awk -F' |\(|\)' ' $9 == "saved" && \
					$7 == "-" { print $5 }' /tmp/dl.log | \
					tail -1 \
				   )
		case $SIZEFACTORSTRING in
			"" | \
			[0-9]) 	logconcolon 'Not enough bandwidth for update task - aborting.'
				cleanup
				return 0
				;;
			"KB/s") SIZEFACTOR=1;;
			"MB/s") SIZEFACTOR=1024;;
			"GB/s") SIZEFACTOR=1048576;;
			*)     	SIZEFACTOR=$((1024*1024*1024));;
		esac
		DLRATE=$(	awk -F' |\(|\)' ' $9 == "saved" && $7 == "-" \
				{ print $4 }' /tmp/dl.log | \
				tail -1
			 )
		BWLIMIT=$(	echo "$DLRATE $SIZEFACTOR $BWLIMITPERCENT" | \
				awk ' { print $1*$2*$3/100 }' | \
				awk -F'.' '{ print $1 }' \
			  ) # outputs integer kilobytes, not rounded
		logconcolon "$(printf 'Determined bandwidth limit: '"'"'%s KB/s'"'" "${BWLIMIT}")"
		DOWNLOADCOMMAND="wget -Nr -l 1 -nd -P ${TEMPDIR} \
				  --progress=bar:force \
				  --limit-rate=${BWLIMIT}k $DOWNLOADURL"

	elif echo "$DOWNLOADURL" | grep -q "^rsync"; then

		DOWNLOADCOMMANDFORTIMESTAMP="rsync -aPv --inplace $DOWNLOADURL/x2go-tce-timestamp \
				  $TEMPDIR"

		check_timestamp
		CTRC=$?
		if [ $CTRC -eq 1 ]; then
			logconcolon 'an error occurred during timestamp download; trying full download instead ...'
		elif [ $CTRC -eq 5 ]; then
			cleanup
			logconcolon "$(printf 'Nothing to do. - Files on server not newer than '"'"'%s'"'"'.' "${RUNNINGSYSTEMNAME}")"
			logconcolon "$(printf '('"'"'%s'"'"' is Version %s - %s).' "${RUNNINGSYSTEMNAME}" "${RUNNINGVERSION}" "$(date --date="@${RUNNINGVERSION}")")"
			return 0 	# current is newest, nothing to do, we want to avoid
					# unneccessary writes to the medium
		else
			: # NOP
		fi
		prepare_tempdir


		# Attempt to determine available bandwidth & to set BWLIMIT accordingly
		logconnlcolon 'Attempting to determine available bandwidth for rsync.'
		rsync -hh -aPv -W --inplace --log-file=/tmp/dl.log $DOWNLOADURL/x2go-tce-initrd.img \
			$TEMPDIR/x2go-tce-initrd.img.new
		mv $TEMPDIR/x2go-tce-initrd.img.new $TEMPDIR/x2go-tce-initrd.img
		SIZEFACTORSTRING=$(	sed -e's_\(. bytes/sec\)_ \1_' /tmp/dl.log | \
					awk '$4 == "sent" && $12 == "bytes/sec" \
					{ print $11 }' \
				   )
		case $SIZEFACTORSTRING in
			"" | \
			[0-9]) 	logconcolon 'Not enough bandwidth for update task - aborting.'
				cleanup
				return 0
				;;
			"K")   	SIZEFACTOR=1;;
			"M")   	SIZEFACTOR=1024;;
			"G")   	SIZEFACTOR=$((1024*1024));;
			*)     	SIZEFACTOR=$((1024*1024*1024));;
		esac
		DLRATE=$(	sed -e's_\(. bytes/sec\)_ \1_' /tmp/dl.log | \
				awk '$4 == "sent" && $12 == "bytes/sec" \
				{ print $10 }')
		BWLIMIT=$(	echo "$DLRATE $SIZEFACTOR $BWLIMITPERCENT" | \
				awk ' { print $1*$2*$3/100 }' | \
				awk -F'.' '{ print $1 }' \
			  ) # outputs integer kilobytes, not rounded
		logconcolon "$(printf 'Determined bandwidth limit: '"'"'%s KB/s'"'" "${BWLIMIT}")"
		DOWNLOADCOMMAND="rsync -aPv --inplace --bwlimit=$BWLIMIT $DOWNLOADURL/ \
				  $TEMPDIR"
	else 
		[ -n "$NTFSROOT" ] && umount $MOUNTPOINT
		logconcolon 'Unsupported download mechanism - aborting.'
		return 1
	fi
	rm /tmp/dl.log



	# Proceed to download from update location
	#

	logconcolon 'starting download ...'
	while ! $DOWNLOADCOMMAND; do
		logconcolon 'an error occurred; sleeping 30 seconds ...'
		sleep 30
		logconcolon 'retrying ...'
	done

	# Now check if these files are different from what we already have in our
	# download directory on the boot medium
	#
	logconcolon "$(printf 'Diff'"'"'ing '"'"'%s'"'"' '"'"'%s'"'"' ...' "${DOWNLOADPATH}" "${TEMPDIR}")"
	if diff -q $DOWNLOADPATH $TEMPDIR \
		>/dev/null

		then
		cleanup
		logconcolon "$(printf 'Nothing to do. - Files on server not newer than '"'"'%s'"'"'.' "${DOWNLOADPATH}")"
		return 0 	# current is newest, nothing to do, we want to avoid
				# unneccessary writes to the medium
	else
		logconcolon 'Differences detected. Continuing ...'
	fi


	# If we made it past that point, it's time to update the boot medium, so let's
	# remount it rw and async for speed
	#
	if mount -o 'remount,rw,async' "${MOUNTPOINT}"; then
		logconcolon "$(printf 'Remounted '"'"'%s'"'"' as rw and async.' "${MOUNTPOINT}")"
	else
		logconcolon "$(printf 'Could not remount '"'"'%s'"'"' as rw and async.' "${MOUNTPOINT}")"
	fi


	# Now, we don't want to copy an index.htm(l) file, so let's do away with that
	#
	rm -f $TEMPDIR/index.ht*


	# move everything over to the boot medium
	#
	logconcolon "$(printf 'Moving %s/* => %s' "${TEMPDIR}" "${DOWNLOADPATH}")"
	# using mv would accumulate clutter in $DOWNLOADPATH if any extra files are present in the source
	rsync -aPv --inplace --delete --modify-window=1 $TEMPDIR/ $DOWNLOADPATH/ && \
	rm -rf $TEMPDIR/*
	if [ -n "$NTFSROOT" ]; then
		logconcolon "$(printf 'NTFSROOT detected. Attempting to mount '"'"'/dev/disk/by-uuid/%s'"'"'.' "${NTFSROOT}")"
		if mount -t 'ntfs-3g' -o 'rw' "/dev/disk/by-uuid/${NTFSROOT}" '/lib/live/mount/ntfsroot'; then
			logconcolon 'Mount successful.'
		else
			logconcolon 'Failed to mount NTFSROOT.'
		fi
	fi


	# let's check if we just downloaded a copy of our running system
	#
	logconcolon "$(printf 'Diff'"'"'ing '"'"'%s'"'"' '"'"'%s'"'" "${DOWNLOADPATH}" "${RUNNINGSYSTEMFULLPATH}")"
	if diff -q $DOWNLOADPATH $RUNNINGSYSTEMFULLPATH >/dev/null && \
		   [ -d "$OTHERSYSTEMFULLPATH" ] ; then
		   [ -n "$NTFSROOT" ] && umount $MOUNTPOINT
		   logconcolon "$(printf 'Nothing to do. Content of %s equals %s.' "${DOWNLOADPATH}" "${RUNNINGSYSTEMNAME}")"
			# now, change mount back to ro and sync
			umount_or_remount_ro
			return 0 # current is newest, nothing to do, 
				 # we want to keep the old system in OTHERSYSTEMFULLPATH
				 # as a fallback
	fi


	# make sure our destination path really exists
	#
	mkdir -p $OTHERSYSTEMFULLPATH


	# let's check if our destination is already up to date or needs updating
	#
	logconcolon "$(printf 'Diff'"'"'ing '"'"'%s'"'"' '"'"'%s'"'" "${DOWNLOADPATH}" "${OTHERSYSTEMFULLPATH}")"
	if diff -q $DOWNLOADPATH $OTHERSYSTEMFULLPATH >/dev/null; then
			[ -n "$NTFSROOT" ] && umount $MOUNTPOINT
			logconcolon "$(printf 'Nothing to do - content of '"'"'%s'"'"' equals '"'"'%s'"'"'.' "${DOWNLOADPATH}" "${OTHERSYSTEMNAME}")"
			return 0 # OTHERSYSTEMFULLPATH is already up to date
	else
		# keep rsyncing until the update is complete
		logconcolon "$(printf 'Copying %s/ => %s ...' "${DOWNLOADPATH}" "${OTHERSYSTEMFULLPATH}")"
		while ! rsync -aPv --inplace --modify-window=1 $DOWNLOADPATH/ $OTHERSYSTEMFULLPATH
			do
			logconcolon 'Sleeping 30 seconds ...'
			sleep 30
			logconcolon 'Retrying ...'
		done
		logconcolon 'done.'
		if rm -rf $DOWNLOADPATH/* ; then
			logconcolon 'INFO: purged download directory to avoid clutter buildup.'
		else
			logconcolon 'ERROR: unable to purge download directory.'
		fi
	fi

	show_versions

	# change default boot to the image we just downloaded and installed
	#
	if [ -n "$SYSLINUXPATH" ]; then
		logconcolon "$(printf 'Changing syslinux default to %s.' "${OTHERSYSTEMNAME}")"
		sed -i -e"/^default/cdefault $OTHERSYSTEMNAME" \
			$SYSLINUXPATH/syslinux.cfg

	elif [ -n "$GRUBPATH" ]; then
		MENULST=$GRUBPATH/menu.lst
		CURRENTDEFAULT=$(awk '/^default/ { print $2 }' $MENULST | tr -d '\r')
		CURRENTTITLEPOSITION=$(grep '^title' $MENULST | 
				       grep -n "${RUNNINGSYSTEMNAME}" |
				       awk -F':' '$2 ~ /'"${RUNNINGSYSTEMNAME}"'/ { print $1 }')
		CURRENTTITLEPOSITION=$((CURRENTTITLEPOSITION-1))
		OTHERTITLEPOSITION=$(grep '^title' $MENULST |
				     grep -n "${OTHERSYSTEMNAME}" |
				     awk -F':' '$2 ~ /'"${OTHERSYSTEMNAME}"'/ { print $1 }')
		OTHERTITLEPOSITION=$((OTHERTITLEPOSITION-1))
		if [ "$CURRENTTITLEPOSITION" = "$CURRENTDEFAULT" ]; then
			logconcolon "$(printf 'Changing GRUB-legacy default to %s ...' "${OTHERTITLEPOSITION}")"
			sed -i -e"/^default/cdefault $OTHERTITLEPOSITION" \
				$MENULST
		else
			logconcolon 'Not changing GRUB-legacy default.'
			logconcolon "$(printf 'Reason: We'"'"'re at boot position '"'"'%s'"'"',' "${CURRENTTITLEPOSITION}")"
			logconcolon "$(printf 'while default is set to position '"'"'%s'"'"'.' "${CURRENTDEFAULT}")"
		fi
	else
		logconcolon 'Unsupported bootloader.'
	fi

	# we're on an async mount point, so let's sync to be safe
	#
	sync


	# umount tempdir to free memory
	#
	if [ -d $TEMPDIR ]; then
		cleanup
	fi


	# now, change mount back to ro and sync
	#
	umount_or_remount_ro

) &

}

LiveAutoUpdateMain

