#!/bin/bash

. '/lib/live/config/common.logging'

TcpPrint ()
{

# Output startup message
#
printf ' %s' 'tcpprint'

if grep -q "\W*tcpprint\W*" /proc/cmdline ; then

        TCPPRINTONLYFROM=$(sed -e 's/ \([^ ]*\)=/\n\1=/g' -e 's/\([^=]["'"'"']\) /\1\n/g' -e 's/ \([^ "'"'"']\)/\n\1/g' /proc/cmdline | \
                           awk -F'=' ' /^tcpprintonlyfrom=/ { print $2 }' | \
		           tr -dc 'a-zA-Z0-9.\-')
	if [ -n "$TCPPRINTONLYFROM" ] ; then
		TCPPRINTONLYFROM="only_from = $TCPPRINTONLYFROM"
	fi
	# Backgrounding
	(

	while ! lsmod | grep -q "^lp"; do
		# Wait till modprobe lp has occurred
		# -> this means /dev is fully populated
		# => USB-Printers can be detected now, too
		sleep 30
	done

	while ! [ -c /dev/tty8 ] ; do
		logcon 'is waiting for tty8 to become available.'
		sleep 2
	done

	PRINTERDEVICES=""
	[ -d /dev/usb ] && PRINTERDEVICES=$(find /dev/usb -type c -name "lp*" | sort)
	PRINTERDEVICES="$PRINTERDEVICES $(find /dev/ -maxdepth 1 -type c -name "lp*" | sort)"

	logtty 'is waiting for a client IP.'

	# Create a listening port for a TCP/9100-RAW-printer
	#
	# printers may be at /dev/lp_ and at /dev/usb/lp_
	PRINTERCOUNT=0
	for PRINTERDEV in $PRINTERDEVICES; do 
		PORTNUMBER=$((PRINTERCOUNT+9100))
		echo "jetdirect${PRINTERCOUNT} ${PORTNUMBER}/tcp" >>/etc/services
		cat >/etc/xinetd.d/jetdirect${PRINTERCOUNT} << JETDIRCONF 
service jetdirect${PRINTERCOUNT}
{
	socket_type = stream
	protocol = tcp
	wait = no
	user = root
	server = /bin/dd
	server_args = of=$PRINTERDEV bs=1024k
	groups = yes
	disable = no
	instances = 1
	$TCPPRINTONLYFROM
}
JETDIRCONF
		logttycolon "$(printf 'Mapping %s => %s' "${PRINTERDEV}" "${PORTNUMBER}")"
		PRINTERCOUNT=$((PRINTERCOUNT+1))
	done

	printf '%s\n' '#Local printer config: Done.' >/etc/xinetd.d/jetdirect

	if ps -C xinetd --no-header >/dev/null ; then
		logttycolon 'xinetd needs to be restarted, trying to do that ...'
		if /etc/init.d/xinetd restart; then
			logttyraw ' success. All done.'
		else
			logttyraw ' error.'
		fi
	else
		logttycolon 'No xinetd restart necessary. All done.'
	fi

	) &
fi
}

TcpPrint
