#!/bin/bash

# shellcheck shell=dash
# vim: syntax=sh:

. '/lib/live/config/common.utils'

EdgeConfig ()
{
	# Output startup message
	#
	echo -n " microsoft-edgeconfig"

	HOMEPAGEURL=$(sed -e 's/ \([^ ]*\)=/\n\1=/g' -e 's/\([^=]["'"'"']\) /\1\n/g' -e 's/ \([^ "'"'"']\)/\n\1/g' /proc/cmdline | \
		      awk -F'=' ' /^homepageurl=/ { print $2 } ')
	if [ -z "$HOMEPAGEURL" ] ; then 
		HOMEPAGEURL='http://www.x2go.org/'
	else
		HOMEPAGEURL=$(echo -e '"'"$(urldecode "$HOMEPAGEURL")"'"' | sed -e 's#|#", "#g')
	fi
	mkdir -p /etc/opt/edge/policies/managed
	mkdir -p /etc/opt/edge/policies/recommended
	cat >/etc/opt/edge/policies/managed/microsoft-edge.json <<MSEDGECONFIG

// Policy template for Linux.
// Documentation for this file can be found at
// https://www.chromium.org/administrators/policy-list-3
// and/or
// https://cloud.google.com/docs/chrome-enterprise/policies/

{
 "AllowFileSelectionDialogs": false,
 "DownloadDirectory": "/home/\${user_name}/Downloads",
 "EditBookmarksEnabled": false,
 "HomepageIsNewTabPage": false,
 "HomepageLocation": [$HOMEPAGEURL],
 "ImportBookmarks": false,
 "ImportHistory": false,
 "ImportHomepage": false,
 "ImportSavedPasswords": false,
 "ImportSearchEngine": false,
 //"ProxyBypassList": "http://www.example1.com,http://www.example2.com,http://internalsite/",
 //"ProxyMode": "direct",
 //"ProxyPacUrl": "http://internal.site/example.pac",
 //"ProxyServer": "123.123.123.123:8080",
 "RestoreOnStartup": 4,
 //   5 = Open New Tab Page
 //   1 = Restore the last session
 //   4 = Open a list of URLs
 "RestoreOnStartupURLs": [$HOMEPAGEURL],
 "ShowHomeButton": true,
 "SyncDisabled": true,
 "TranslateEnabled": false
}
MSEDGECONFIG

	if grep -q ' *kioskbrowser *' /proc/cmdline ; then
		echo "#!/bin/bash" > /usr/local/bin/microsoft-edge
		echo "$(which microsoft-edge)"' --kiosk "$@" --edge-kiosk-type=public-browsing --no-first-run --no-default-browser-check' >> /usr/local/bin/microsoft-edge
		chmod 755 /usr/local/bin/microsoft-edge
		[ -f /usr/share/applications/microsoft-edge.desktop ] && \
		sed -e '/^Exec=/c Exec=/usr/local/bin/microsoft-edge' -i /usr/share/applications/microsoft-edge.desktop
	fi
}

if which microsoft-edge >/dev/null; then
       	EdgeConfig
fi
