#!/bin/bash

function urldecode() {
	        : "${*//+/ }"; echo -e "${_//%/\\x}";
	}

FirefoxConfig ()
{
	# Output startup message
	#
	echo -n " firefoxconfig"

	HOMEPAGEURL=$(sed -e 's/ \([^ ]*\)=/\n\1=/g' -e 's/\([^=]["'"'"']\) /\1\n/g' -e 's/ \([^ "'"'"']\)/\n\1/g' /proc/cmdline | \
		      awk -F'=' ' /^homepageurl=/ { print $2 } ')
	if [ -z "$HOMEPAGEURL" ] ; then 
		HOMEPAGEURL='http://www.x2go.org/'
	else
		HOMEPAGEURL=$(echo -e "$(urldecode "$HOMEPAGEURL")")
	fi
	sed -i	-e '/"browser.newtabpage.activity-stream.aboutHome.enabled"/d' \
		-e '/"browser.rights.3.shown"/d' \
		-e '/"browser.rights.override"/d' \
		-e '/"browser.shell.checkDefaultBrowser"/d' \
		-e '/"browser.startup.homepage_override.mstone"/d' \
		-e '/"browser.startup.homepage"/d' \
		-e '/"browser.usedOnWindows10/d' \
		-e '/"datareporting.policy.dataSubmissionPolicyBypassNotification"/d' \
		-e '/"datareporting.policy.firstRunURL"/d' \
		-e '/"privacy.donottrackheader.enabled"/d' \
		-e '/"toolkit.telemetry.prompted"/d' \
		-e '/"browser.translations.enable"/d' \
		/etc/firefox-esr/firefox-esr.js
	cat >>/etc/firefox-esr/firefox-esr.js <<FIREFOXCONFIG

//set some sane browser defaults
lockPref("browser.newtabpage.activity-stream.aboutHome.enabled", false); 
lockPref("browser.rights.3.shown", true);
lockPref("browser.rights.override", true);
lockPref("browser.shell.checkDefaultBrowser", false);
lockPref("browser.startup.homepage_override.mstone","ignore");
lockPref("browser.startup.homepage", "$HOMEPAGEURL");
lockPref("browser.usedOnWindows10", true);
lockPref("datareporting.policy.dataSubmissionPolicyBypassNotification", true);
lockPref("datareporting.policy.firstRunURL", ""); 
lockPref("privacy.donottrackheader.enabled", true);
lockPref("toolkit.telemetry.prompted", 2); 
pref("browser.translations.enable", false);
FIREFOXCONFIG
}

if which firefox-esr >/dev/null || which firefox >/dev/null; then
	FirefoxConfig
fi
