#!/bin/bash

# shellcheck shell=dash
# vim: syntax=sh:

. '/lib/live/config/common.utils'

FirefoxConfig ()
{
	# Output startup message
	#
	printf ' %s' 'firefoxconfig'

	HOMEPAGEURL="$(sed -e 's/ \([^ ]*\)=/\n\1=/g' -e 's/\([^=]["'"'"']\) /\1\n/g' -e 's/ \([^ "'"'"']\)/\n\1/g' '/proc/cmdline' | \
		       awk -F'=' ' /^homepageurl=/ { print $2 } ')"
	if [ -z "${HOMEPAGEURL}" ] ; then
		HOMEPAGEURL='http://www.x2go.org/'
	else
		HOMEPAGEURL="$(printf '%s\n' "$(urldecode "${HOMEPAGEURL}")")"
	fi
	sed -i	-e '/"browser.newtabpage.activity-stream.aboutHome.enabled"/d' \
		-e '/"browser.rights.3.shown"/d' \
		-e '/"browser.rights.override"/d' \
		-e '/"browser.shell.checkDefaultBrowser"/d' \
		-e '/"browser.startup.homepage_override.mstone"/d' \
		-e '/"browser.startup.homepage"/d' \
		-e '/"browser.uiCustomization.state/d' \
		-e '/"browser.usedOnWindows10/d' \
		-e '/"datareporting.policy.dataSubmissionPolicyBypassNotification"/d' \
		-e '/"datareporting.policy.firstRunURL"/d' \
		-e '/"privacy.donottrackheader.enabled"/d' \
		-e '/"toolkit.telemetry.prompted"/d' \
		-e '/"browser.translations.enable"/d' \
		'/etc/firefox-esr/firefox-esr.js'
	cat >> '/etc/firefox-esr/firefox-esr.js' <<FIREFOXCONFIG

//set some sane browser defaults
lockPref("browser.newtabpage.activity-stream.aboutHome.enabled", false);
lockPref("browser.rights.3.shown", true);
lockPref("browser.rights.override", true);
lockPref("browser.shell.checkDefaultBrowser", false);
lockPref("browser.startup.homepage_override.mstone","ignore");
lockPref("browser.startup.homepage", "${HOMEPAGEURL}");
lockPref("browser.uiCustomization.state", '{"placements":{"widget-overflow-fixed-list":[],"unified-extensions-area":[],"nav-bar":["back-button","forward-button","stop-reload-button","customizableui-special-spring1","urlbar-container","customizableui-special-spring2","save-to-pocket-button","downloads-button","fxa-toolbar-menu-button","unified-extensions-button","ublock0_raymondhill_net-browser-action"],"toolbar-menubar":["menubar-items"],"TabsToolbar":["firefox-view-button","tabbrowser-tabs","new-tab-button","alltabs-button"],"PersonalToolbar":["import-button","personal-bookmarks"]},"seen":["save-to-pocket-button","developer-button","ublock0_raymondhill_net-browser-action"],"dirtyAreaCache":["nav-bar","unified-extensions-area","PersonalToolbar","toolbar-menubar","TabsToolbar"],"currentVersion":20,"newElementCount":2}');
lockPref("browser.usedOnWindows10", true);
lockPref("datareporting.policy.dataSubmissionPolicyBypassNotification", true);
lockPref("datareporting.policy.firstRunURL", ""); 
lockPref("privacy.donottrackheader.enabled", true);
lockPref("toolkit.telemetry.prompted", 2); 
pref("browser.translations.enable", false);
FIREFOXCONFIG

	if grep -q ' *kioskbrowser *' /proc/cmdline ; then
		echo "#!/bin/bash" > /usr/local/bin/firefox-esr
		echo '$(which firefox-esr) -kiosk $@' >> /usr/local/bin/firefox-esr
		chmod 755 /usr/local/bin/firefox
		echo "#!/bin/bash" > /usr/local/bin/firefox
		echo '$(which firefox) -kiosk $@' >> /usr/local/bin/firefox
		chmod 755 /usr/local/bin/firefox
	fi
}

if command -v 'firefox-esr' >/dev/null || command -v 'firefox' >/dev/null; then
	FirefoxConfig
fi
