#!/bin/bash
# set custom launcher button icon
export TERM=linux;
LAUNCHICONURL=$(sed -e 's/ \([^ ]*\)=/\n\1=/g' -e 's/\([^=]["'"'"']\) /\1\n/g' -e 's/ \([^ "'"'"']\)/\n\1/g' /proc/cmdline | \
	awk -F'=' ' /^launchicon=/ { print $2 }' | \
	tr -dc 'a-zA-Z0-9.:/?%_\-')
LAUNCHICONDESTINATION=/etc/x2go/x2golauncher_downloaded.png

if [ -n "$LAUNCHICONURL" ] ; then

	if [ "$METHOD" = "loopback" ] || [ "$METHOD" = "none" ]; then
		exit 0
	fi

	(
		while ! [ -c /dev/tty8 ] ; do
			echo -en "\n$(date +'%F | %T | ')'$0' is waiting for tty8 to become available."
			sleep 2
		done
		while [ -z "$(hostname -I)" ] ; do
			echo -en "\n$(date +'%F | %T | ')'$0' is waiting for a client IP." | tee -a /dev/tty8
			sleep 2
		done

		echo -en "\n$(date +'%F | %T | ')'$0': Attempting launcher icon download ..." | tee -a /dev/tty8
		if echo "$LAUNCHICONURL" | grep -q "^tftp://" ; then
			LAUNCHICONSERVER=$(echo "$LAUNCHICONURL" | sed 's#^tftp://\([^/;]*\)/.*$#\1#' )
			LAUNCHICONPATH=$(echo "$LAUNCHICONURL" | sed 's#^tftp://[^/;]*/\([^;]*\)$#\1#' )
			if [ -n "$LAUNCHICONSERVER" ] && [ -n "$LAUNCHICONPATH" ] ; then
				while ! atftp "$LAUNCHICONSERVER" -g -r "$LAUNCHICONPATH" -l ${LAUNCHICONDESTINATION}.tmp ; do
					echo -en "\n$(date +'%F | %T | ')still waiting for launcher icon download (tftp) ..." | tee -a /dev/tty8
					sleep 5
				done
			fi
		else
			while ! wget -q -O ${LAUNCHICONDESTINATION}.tmp "$LAUNCHICONURL" ; do
				echo -en "\n$(date +'%F | %T | ')still waiting for launcher icon download (wget) ..." | tee -a /dev/tty8
				sleep 5 
			done
		fi

		echo -en "\n$(date +'%F | %T | ')'$0': launcher icon download complete." | tee -a /dev/tty8
		if [ -s ${LAUNCHICONDESTINATION}.tmp ] ; then
			mv ${LAUNCHICONDESTINATION}.tmp $LAUNCHICONDESTINATION
			ln -f $LAUNCHICONDESTINATION /etc/x2go/x2golauncher.png
		fi
	) &
fi
